### ISSUE TITLE
ubuntu 16.04 docker 无法启动

### ISSUE THREAD

**Issue by aheadlead** [strahe/dnspod-ddns#9]
$ sudo docker logs a70211ceb4e7
Traceback (most recent call last):
  File "ddns.py", line 13, in <module>
    from config import read_config, save_config, check_config, cfg
ModuleNotFoundError: No module named 'config'
Traceback (most recent call last):
  File "ddns.py", line 13, in <module>
    from config import read_config, save_config, check_config, cfg
ModuleNotFoundError: No module named 'config'
Traceback (most recent call last):
  File "ddns.py", line 13, in <module>
    from config import read_config, save_config, check_config, cfg
ModuleNotFoundError: No module named 'config'
Traceback (most recent call last):
  File "ddns.py", line 13, in <module>
    from config import read_config, save_config, check_config, cfg
ModuleNotFoundError: No module named 'config'
Traceback (most recent call last):
  File "ddns.py", line 13, in <module>
    from config import read_config, save_config, check_config, cfg
ModuleNotFoundError: No module named 'config'

需要什么信息请补充

**Comment by strahe** [comment]
你好, 更新了docker image, 麻烦再试一下, 谢谢
